- name: Creating blackbox_exporter user group
  group: name="{{groupId}}"
  become: true

- name: Creating blackbox_exporter user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Install prometheus blackbox exporter
  unarchive:
    src: "https://nexus.cfrm.dev.local/repository/devops-artifacts/prometheus/blackbox_exporter/blackbox_exporter-{{ blackbox_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus blackbox exporter file to bin
  copy:
    src: "/tmp/blackbox_exporter-{{ blackbox_version }}.linux-amd64/blackbox_exporter"
    dest: "{{ blackbox_usr_local_bin }}/blackbox_exporter"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Delete blackbox exporter tmp folder
  file:
    path: '/tmp/blackbox_exporter-{{ blackbox_version }}.linux-amd64'
    state: absent

- name: Creates directory
  file: 
    path: "{{ blackbox_data }}"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Copy blackbox exporter config file
  template:
    src: blackbox.yml.j2
    dest: "{{ blackbox_data }}/blackbox.yml"
    owner: "{{userId}}"
    group: "{{groupId}}"

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: "{{ blackbox_etc_systemd }}/blackbox_exporter.service"
  notify: event_restart_blackbox_exporter

- name: Start blackbox_exporter service
  service:
    name: "{{ blackbox_serviceName }}"
    state: started
    enabled: yes

- name: Check if blackbox_exporter is accessible
  uri:
    url: http://"{{ localhost }}":"{{ blackbox_port }}"
    method: GET
    status_code: 200

- name: Restart prometheus service
  service:
    name: "{{ prometheus_serviceName }}"
    state: restarted
    enabled: yes