---
# defaults file for roles/grafana
blackbox_rpm_file_url: "https://nexus.cfrm.dev.local/repository/devops-artifacts/prometheus/blackbox_exporter/blackbox_exporter-{{ blackbox_version }}.linux-amd64.tar.gz"
blackbox_version: "0.22.0"

blackbox_serviceName: "blackbox_exporter"
userId: "blackbox_exporter"
groupId: "blackbox_exporter"
prometheus_serviceName: "prometheus"

blackbox_usr_local_bin: "/usr/local/bin"
blackbox_data: "/data/blackbox_exporter"
blackbox_etc_systemd: "/etc/systemd/system"
blackbox_etc: "/etc/blackbox_exporter"
localhost: "localhost"
blackbox_port: "9115"