{
 "title": "Apache Artemis",
 "description": "Dashboard for monitoring Apache Artemis",
 "tags": [ "apache artemis" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "IP:Port",
    "query": "label_values(jvm_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "queues ratio testing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(artemis_messages_acknowledged / artemis_messages_added)*100"
    }
   ]
  },
  {
   "title": "Started",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "artemis_started{job=\"cfrm_artemis\"}"
    }
   ]
  },
  {
   "title": "Free File Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$instance\",job=\"cfrm_artemis\"} - process_open_fds{instance=\"$instance\",job=\"cfrm_artemis\"}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_info{instance=\"$instance\", job=\"cfrm_artemis\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "artemis_uptime_millis{job=\"cfrm_artemis\"} / 1000 / 60"
    }
   ]
  },
  {
   "title": "Journal Buffer Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "artemis_journal_buffer_size{instance=\"$instance\", job=\"cfrm_artemis\"}"
    },
    {}
   ]
  },
  {
   "title": "Address Paging",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "artemis_paging{job=\"cfrm_artemis\"}"
    }
   ]
  },
  {
   "title": "Journal Buffer Timeout",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "artemis_journal_buffer_timeout{instance=\"$instance\", job=\"cfrm_artemis\"}"
    },
    {}
   ]
  },
  {
   "title": "Journal Max I/O",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "artemis_journal_max_io{instance=\"$instance\", job=\"cfrm_artemis\"}"
    },
    {}
   ]
  },
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_message_count{instance=\"10.16.42.63:9779\", job=\"cfrm_artemis\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Connections and Consumers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_connection_count{instance=\"$instance\", job=\"cfrm_artemis\"}",
     "legendFormat": "Connection Count"
    },
    {
     "expr": "artemis_consumer_count{instance=\"$instance\", job=\"cfrm_artemis\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Artemis Address Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "artemis_address_size{job=\"cfrm_artemis\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"cfrm_artemis\"}",
     "legendFormat": "{{ area }} "
    }
   ]
  },
  {
   "title": "JVM Memory Pool Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_pool_bytes_used", "legendFormat": "{{ pool }} " }
   ]
  },
  {
   "title": "JVM GC Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"cfrm_artemis\"}",
     "legendFormat": "{{ gc }}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"cfrm_artemis\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "jvm_threads_peak{instance=\"$instance\",job=\"cfrm_artemis\"}",
     "legendFormat": "Peak"
    }
   ]
  }
 ]
}