{
 "title": "CFRM JOBS DASHBOARD",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Jobs Executions by Job and Tenant in the last hour",
   "type": "graph",
   "description": "Jobs Executions by Job and Tenant in the last hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(investigationcenter_jobs_executioncount[1h])",
     "legendFormat": "{{exported_job}}{{tenantid}}"
    }
   ]
  },
  {
   "title": "Generate Alerts Latest Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "investigationcenter_jobs_latestduration {exported_job=\"generate-alerts-and-risks\"}",
     "legendFormat": "{{tenantid}}"
    }
   ]
  },
  {
   "title": "long running jobs (3stddev) ?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "investigationcenter_jobs_latestduration > investigationcenter_jobs_meanduration + stddev_over_time(investigationcenter_jobs_latestduration[1w])*3",
     "legendFormat": "{{exported_job}} {{tenantid}}"
    }
   ]
  },
  {
   "title": "Jobs that did not run in the last 24H",
   "type": "table",
   "description": "Jobs that did not run in the last 24H (but did run last week)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase (investigationcenter_jobs_executioncount[24h]) < 1 and increase(investigationcenter_jobs_executioncount[24h] offset 1w) > 0",
     "legendFormat": "{{exported_job}} - {{tenantid}}"
    }
   ]
  },
  {
   "title": "JOBS MAXIMAL DURATION (all time)",
   "type": "table",
   "description": "JOBS MAXIMAL DURATION (all time)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "investigationcenter_jobs_maxduration"
    }
   ]
  }
 ]
}