{
 "title": "ElasticSearch",
 "description": "DIsplay ElasticSearch key metrics from Prometheus",
 "tags": [
  "prometheus",
  "elasticsearch"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 1h, 6h, 1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(es_cluster_status, cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(es_jvm_uptime_seconds{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "shard_type",
    "label": "Shard Type",
    "query": "label_values(es_cluster_shards_number, type)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_status{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 1 },
   "targets": [
    { "expr": "(es_cluster_status == 0) +1", "legendFormat": "GREEN" },
    { "expr": "es_cluster_status == 1", "legendFormat": "YELLOW" },
    { "expr": "(es_cluster_status == 2) - 1", "legendFormat": "RED" }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_nodes_number{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_datanodes_number{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_pending_tasks_number{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$shard_type shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_shards_number{cluster=\"$cluster\",type=\"$shard_type\"})"
    }
   ]
  },
  {
   "title": "$shard_type shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 4.8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_shards_number{cluster=\"$cluster\",type=\"$shard_type\"})"
    }
   ]
  },
  {
   "title": "$shard_type shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 9.6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_shards_number{cluster=\"$cluster\",type=\"$shard_type\"})"
    }
   ]
  },
  {
   "title": "$shard_type shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 14.399999999999999, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_shards_number{cluster=\"$cluster\",type=\"$shard_type\"})"
    }
   ]
  },
  {
   "title": "$shard_type shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 19.2, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(es_cluster_shards_number{cluster=\"$cluster\",type=\"$shard_type\"})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "es_os_cpu_percent{cluster=\"$cluster\", node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "es_os_mem_used_bytes{cluster=\"$cluster\", node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percentunit", "label": "Disk" }
   ],
   "targets": [
    {
     "expr": "1 - es_fs_path_available_bytes{cluster=\"$cluster\",node=~\"$node\"} / es_fs_path_total_bytes{cluster=\"$cluster\",node=~\"$node\"}",
     "legendFormat": "{{node}} - {{path}}"
    }
   ]
  },
  { "title": "Documents and Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Documents indexing rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "increase(es_indices_indexing_index_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Indexing latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "increase(es_indices_indexing_index_time_seconds{cluster=\"$cluster\", node=~\"$node\"}[$interval]) / increase(es_indices_indexing_index_count{cluster=\"$cluster\", node=~\"$node\"}[$interval]) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Search rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Searches/s" }
   ],
   "targets": [
    {
     "expr": "increase(es_indices_search_query_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Search latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_search_query_time_seconds{cluster=\"$cluster\", node=~\"$node\"}[$interval]) / rate(es_indices_search_query_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Documents count (with replicas)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Documents" }
   ],
   "targets": [
    {
     "expr": "es_indices_doc_number{cluster=\"$cluster\", node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Documents deleting rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "increase(es_indices_doc_deleted_number{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Documents merging rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Merges/s" }
   ],
   "targets": [
    {
     "expr": "increase(es_indices_merges_total_docs_count{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Field data memory size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "es_indices_fielddata_memory_size_bytes{cluster=\"$cluster\", node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_fielddata_evictions_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "es_indices_querycache_cache_size_bytes{cluster=\"$cluster\", node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Evictions/s" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_querycache_evictions_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Query cache hits",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Hits/s" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_querycache_hit_count{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Query cache misses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Misses/s" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_querycache_miss_number{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Indexing throttling",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_indexing_throttle_time_seconds{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Merging throttling",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(es_indices_merges_total_throttled_time_seconds{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bytes", "label": "Heap" }
   ],
   "targets": [
    {
     "expr": "es_jvm_mem_heap_used_bytes{cluster=\"$cluster\", node=~\"$node\"}",
     "legendFormat": "{{node}} - heap used"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "GC/s" }
   ],
   "targets": [
    {
     "expr": "increase(es_jvm_gc_collection_count{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "increase(es_jvm_gc_collection_time_seconds{cluster=\"$cluster\", node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}} - {{gc}}"
    }
   ]
  }
 ]
}