{
 "title": "Application KPIs",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Generated Alerts in the Last Day",
   "type": "singlestat",
   "description": "Generated Alerts in the Last Day",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "increase(total_alerts[1d])" },
    {}
   ]
  },
  {
   "title": "Generated Alerts in an Average Day",
   "type": "singlestat",
   "description": "Generated Alerts in the last 7d",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(increase(total_alerts[1d] offset 1d) + increase(total_alerts[1d] offset 2d)+ increase(total_alerts[1d] offset 3d) + increase(total_alerts[1d] offset 4d))/4"
    }
   ]
  },
  {
   "title": "Received Transactions in the Last Day",
   "type": "singlestat",
   "description": "Received Transactions in the Last day",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "increase(transactions[1d])" }
   ]
  },
  {
   "title": "Received Transactions in an average day",
   "type": "singlestat",
   "description": "Received Transactions in the Last day",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(increase(transactions[1d] offset 1d) + increase(transactions[1d] offset 2d) + increase(transactions[1d] offset 3d) + increase(transactions[1d] offset 4d)+ increase(transactions[1d] offset 5d)+ increase(transactions[1d] offset 6d) + increase(transactions[1d] offset 7d)) / 7"
    }
   ]
  },
  {
   "title": "GENERATED ALERTS BY TENANTS  (1d)",
   "type": "graph",
   "description": "GENERATED ALERTS BY TENANTS (last 1d)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "ceil(increase(alerts[1d]))", "legendFormat": "{{tenant_id}} 1d" }
   ]
  },
  {
   "title": "HOURLY RATE OF INCOMING TRANSACTIONS BY TENANT (1d)",
   "type": "graph",
   "description": "INCOMING TRANSACTIONS BY TENANT",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant_id) (increase (transactions_grouped[1h])) ",
     "legendFormat": "{{tenant_id}} 1d"
    }
   ]
  },
  {
   "title": "INCOMING TRANSACTIONS BY TYPE (1d)",
   "type": "graph",
   "description": "INCOMING TRANSACTIONS BY TYPE                (cross system, 1h)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (object_type) (increase(transactions_grouped[1d]))",
     "legendFormat": "{{object_type}} 1d"
    },
    {}
   ]
  }
 ]
}