---
# defaults file for roles/grafana

alertmanager_serviceName: "alertmanager"
prometheus_serviceName: "prometheus"
userId: "alertmanager"
groupId: "alertmanager"
alertmanager_version: "0.24.0"
localhost: "localhost"
alertmanager_port: "9093"

alert_usr_local_bin: "/usr/local/bin"
alertmanager_etc: "/etc/alertmanager"
var_lib_alertmanager: "/var/lib/alertmanager"
alertmanager_etc_systemd: "/etc/systemd/system"
etc_atmool: "/etc/amtool"
